# render.yaml
# A robust blueprint for deploying Plausible Analytics on Render.
# This file defines all necessary services in one place.

services:
  # 1. PostgreSQL Database for application data (accounts, sites).
  - type: psql
    name: plausible-db
    plan: free # The 'Free' plan is sufficient for starting out.
    postgresVersion: 14

  # 2. ClickHouse Database for high-volume event data.
  # This runs in a Docker container as a Private Service.
  - type: privateService
    name: clickhouse-db
    plan: starter # IMPORTANT: The 'Free' plan is not powerful enough. Use 'Starter' or higher.
    image:
      url: clickhouse/clickhouse-server:23.8 # Using a specific, stable version.
    disks:
      - name: clickhouse-data
        mountPath: /var/lib/clickhouse
        sizeGB: 10 # Start with 10GB; can be increased later.
    envVars:
      - key: CLICKHOUSE_DB
        value: plausible
      - key: CLICKHOUSE_USER
        value: plausible
      - key: CLICKHOUSE_PASSWORD
        generateValue: true # Render will securely generate and manage this password.

  # 3. The Plausible Web Application.
  - type: web
    name: plausible
    plan: starter # 'Starter' is recommended for production.
    env: elixir
    healthCheckPath: /api/health
    buildCommand: |
      # This block runs during every build to prepare the app.
      # It installs dependencies, builds assets, and prepares the database schema.
      mix local.rebar --force
      mix local.hex --force
      mix deps.get --only prod
      mix deps.compile
      npm install --prefix ./assets
      npm run deploy --prefix ./assets
      mix compile
      mix phx.digest
      mix ecto.setup
    startCommand: "mix phx.server"
    envVars:
      # Link to the PostgreSQL database we defined above.
      - key: DATABASE_URL
        fromService:
          type: psql
          name: plausible-db
          property: connectionString
      # Link to the ClickHouse database.
      - key: CLICKHOUSE_DATABASE_URL
        fromService:
          type: privateService
          name: clickhouse-db
          envVarKey: CLICKHOUSE_DATABASE_URL
      # These two variables MUST be set manually in the Render Dashboard after the first deploy.
      - key: BASE_URL
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      # This key is used for two-factor authentication and is generated automatically.
      - key: TOTP_ENCRYPTION_KEY
        generateValue: true
